version: 2

jobs:
  build:
    macos:
      xcode: 12.4.0
    environment:
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Run tests
          command: bundle exec fastlane $FASTLANE_LANE
          environment:
            SCAN_DEVICE: iPhone 8
            SCAN_SCHEME: Fountain
